### ISSUE TITLE
Fallo al cargar el modulo con zef

### ISSUE THREAD

**Issue by thejosess** [JJ/raku-array-shaped-console#1]
Al ejecutar zef install Array::Shaped::Console te devuelve un error: 
 Failed test 'Array::Shaped::Console module can be use-d ok'
[Array::Shaped::Console] # at t/01-basic.t line 4.

![imagen](https://user-images.githubusercontent.com/37021204/77173721-3e514500-6ac0-11ea-8104-13f17491ddae.png)

**Comment by JJ** [comment]
Ok, I'll get to it now.

**Comment by JJ** [comment]
Can you please tell me the Raku version you're using?

**Comment by thejosess** [comment]
Raku v2020.01

**Comment by JJ** [comment]
OK, if it's fixed now with the latest version, please close the issue.
